import type { LinkingOptions } from '@react-navigation/native';

export const linking: LinkingOptions<ReactNavigation.RootParamList> = {
  prefixes: [],
  config: {
    screens: {
      Landing: '',
      Login: 'login',
      Register: 'register',
      Callback: 'callback',
      Onboarding: 'onboarding',
      Dashboard: 'dashboard',
      Challenges: 'challenges',
      Leaderboard: 'leaderboard',
      Profile: 'profile',
      Settings: 'settings',
      Arena: 'arena/:challengeId',
      Replay: 'replay/:attemptId',
      DailyChallenge: 'daily',
      Assessments: 'assessments',
      AssessmentBuilder: 'assessments/build/:assessmentId?',
      AssessmentResultsDashboard: 'assessments/:assessmentId/results',
      AssessmentLanding: 'assess/:token',
      AssessmentFlow: 'assess/session/:sessionId',
      AssessmentResults: 'results/:shareToken',
      Teams: 'teams',
      GuestArena: 'try/:challengeId',
      PublicProfile: 'u/:username',
      Share: 'share/:attemptId',
      Certificate: 'cert/:shareToken',
      OrgManagement: 'org/:orgId?',
      OrgJoin: 'org/join/:token',
      Models: 'models',
      ModelDetail: 'models/:modelId',
      NotFound: '*',
    },
  },
};
