app = "ruwt"
primary_region = "iad"

[experimental]
  cmd = ["bun", "run", "src/index.ts"]

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  PORT = "3000"

[deploy]
  release_command = "bun run db:migrate"
  release_command_timeout = "5m"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

