-- D1 seed: challenges. Generated by scripts/seed-d1.ts
-- Run: npx wrangler d1 execute <DB_NAME> --remote --file=./scripts/seed-d1.sql

INSERT OR REPLACE INTO challenges (id, title, description, difficulty, starter_code, test_cases, exec_time_limit, exec_memory_limit, max_tokens, max_cost, wall_clock_limit) VALUES ('two-sum', 'Two Sum', 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: nums[0] + nums[1] == 9, so return [0, 1].', 'easy', 'function twoSum(nums, target) {
  // Your code here
}

module.exports = { twoSum };', '[{"input":"[2,7,11,15]\n9","expectedOutput":"[0,1]"},{"input":"[3,2,4]\n6","expectedOutput":"[1,2]"},{"input":"[3,3]\n6","expectedOutput":"[0,1]"}]', 5000, 256, 50000, 1000, 1800);
INSERT OR REPLACE INTO challenges (id, title, description, difficulty, starter_code, test_cases, exec_time_limit, exec_memory_limit, max_tokens, max_cost, wall_clock_limit) VALUES ('fizzbuzz', 'FizzBuzz', 'Write a function that returns an array of strings from 1 to n based on the following rules:
- For multiples of 3, return "Fizz"
- For multiples of 5, return "Buzz"
- For multiples of both 3 and 5, return "FizzBuzz"
- For all other numbers, return the number as a string

Example:
Input: n = 15
Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]', 'easy', 'function fizzBuzz(n) {
  // Your code here
}

module.exports = { fizzBuzz };', '[{"input":"3","expectedOutput":"[\"1\",\"2\",\"Fizz\"]"},{"input":"5","expectedOutput":"[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\"]"},{"input":"15","expectedOutput":"[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\",\"Fizz\",\"7\",\"8\",\"Fizz\",\"Buzz\",\"11\",\"Fizz\",\"13\",\"14\",\"FizzBuzz\"]"}]', 5000, 256, 30000, 500, 900);
INSERT OR REPLACE INTO challenges (id, title, description, difficulty, starter_code, test_cases, exec_time_limit, exec_memory_limit, max_tokens, max_cost, wall_clock_limit) VALUES ('valid-parentheses', 'Valid Parentheses', 'Given a string s containing just the characters ''('', '')'', ''{'', ''}'', ''['' and '']'', determine if the input string is valid.

An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.

Example:
Input: s = "()[]{}"
Output: true

Input: s = "(]"
Output: false', 'medium', 'function isValid(s) {
  // Your code here
}

module.exports = { isValid };', '[{"input":"()","expectedOutput":"true"},{"input":"()[]{}","expectedOutput":"true"},{"input":"(]","expectedOutput":"false"},{"input":"([)]","expectedOutput":"false"},{"input":"{[]}","expectedOutput":"true"}]', 5000, 256, 75000, 2000, 1800);
INSERT OR REPLACE INTO challenges (id, title, description, difficulty, starter_code, test_cases, exec_time_limit, exec_memory_limit, max_tokens, max_cost, wall_clock_limit) VALUES ('merge-sorted-arrays', 'Merge Sorted Arrays', 'You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.

Merge nums1 and nums2 into a single array sorted in non-decreasing order.

The final sorted array should be stored inside nums1. To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that should be merged, and the last n elements are set to 0.

Return the merged array.

Example:
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]', 'medium', 'function merge(nums1, m, nums2, n) {
  // Your code here
  return nums1;
}

module.exports = { merge };', '[{"input":"[1,2,3,0,0,0]\n3\n[2,5,6]\n3","expectedOutput":"[1,2,2,3,5,6]"},{"input":"[1]\n1\n[]\n0","expectedOutput":"[1]"},{"input":"[0]\n0\n[1]\n1","expectedOutput":"[1]"}]', 5000, 256, 75000, 2000, 1800);
INSERT OR REPLACE INTO challenges (id, title, description, difficulty, starter_code, test_cases, exec_time_limit, exec_memory_limit, max_tokens, max_cost, wall_clock_limit) VALUES ('longest-substring-without-repeating', 'Longest Substring Without Repeating Characters', 'Given a string s, find the length of the longest substring without repeating characters.

Example:
Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.

Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.', 'hard', 'function lengthOfLongestSubstring(s) {
  // Your code here
}

module.exports = { lengthOfLongestSubstring };', '[{"input":"abcabcbb","expectedOutput":"3"},{"input":"bbbbb","expectedOutput":"1"},{"input":"pwwkew","expectedOutput":"3"},{"input":"","expectedOutput":"0"}]', 5000, 256, 100000, 5000, 2700);